name: portofolio
description: A new Flutter project.

publish_to: "none"

## Web Develop
# flutter run -d chrome --web-port 5000
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.0.1
  cached_network_image: ^3.1.0+1
  cloud_firestore: ^3.1.0
  dartz: ^0.10.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_storage: ^10.1.0
  flutter_bloc: ^8.0.0
  flutter_signin_button: ^2.0.0
  get: ^4.3.8
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  freezed_annotation: ^1.0.0
  image_picker: ^0.8.4+4
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  pull_to_refresh: ^2.0.0
  responsive_framework: ^0.1.5
  rxdart: ^0.27.3
  equatable: ^2.0.3
  fluttertoast: ^8.0.8
  animated_text_kit: ^4.2.1 

  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^1.0.0
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5 #flutter pub run build_runner watch --delete-conflicting-outputs
  flutter_launcher_icons: ^0.9.2 #flutter pub run flutter_launcher_icons:main
  change_app_package_name: ^1.0.0 #flutter pub run change_app_package_name:main com.new.package.name
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
